---
- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Reboot System
  ansible.builtin.reboot:
    msg: "Rebooting to apply kernel hardening metrics."

- name: Update GRUB
  ansible.builtin.command: update-grub

- name: Restart Auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
    use: service

- name: Restart Chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
